# Generated by Django 6.0.4 on 2026-05-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_userprofile_is_moderator'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sx_rating_avg',
            field=models.FloatField(default=0.0),
        ),
    ]
