# Generated by Django 6.0.4 on 2026-05-17 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride_share', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ridepost',
            old_name='location',
            new_name='starting_location',
        ),
    ]
