# Generated by Django 6.0.4 on 2026-05-18 02:53

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_share', '0002_rename_location_ridepost_starting_location'),
        ('threads', '0009_threadmessage_is_pinned'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ridepost',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='ridepost',
            name='passenger_count',
        ),
        migrations.AddField(
            model_name='ridepost',
            name='destination_location',
            field=models.CharField(blank=True, default='United International University, Madani Ave, Dhaka', help_text='Destination or landmark', max_length=255),
        ),
        migrations.AddField(
            model_name='ridepost',
            name='direction',
            field=models.CharField(choices=[('to_university', 'Going to University'), ('to_home', 'Going Home')], default='to_university', help_text='Are you going to university or home?', max_length=20),
        ),
        migrations.AddField(
            model_name='ridepost',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 18, 2, 52, 46, 232155, tzinfo=datetime.timezone.utc), help_text='Post expires/closes after this time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ridepost',
            name='max_capacity',
            field=models.PositiveIntegerField(default=1, editable=False, help_text='Auto-set from transport method'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ridepost',
            name='notes',
            field=models.TextField(blank=True, help_text='Anything riders should know'),
        ),
        migrations.AddField(
            model_name='ridepost',
            name='safety_mode',
            field=models.BooleanField(default=False, help_text='When enabled, only women can request to join'),
        ),
        migrations.AlterField(
            model_name='ridepost',
            name='departure_time',
            field=models.DateTimeField(help_text='When you plan to leave your starting location'),
        ),
        migrations.AlterField(
            model_name='ridepost',
            name='starting_location',
            field=models.CharField(help_text='Your pickup area or landmark (e.g. Badda AAMRA Gate)', max_length=255),
        ),
        migrations.AlterField(
            model_name='ridepost',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='ridepost',
            name='transport_method',
            field=models.CharField(choices=[('car', 'Car'), ('rickshaw', 'Rickshaw'), ('cng', 'CNG'), ('microbus', 'MICROBUS')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ridepost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RideGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('forming', 'Forming'), ('confirmed', 'Confirmed'), ('in_transit', 'In Transit'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='forming', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ride_post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ride_group', to='ride_share.ridepost')),
                ('thread', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ride_group', to='threads.thread')),
            ],
        ),
        migrations.CreateModel(
            name='RideJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_size', models.PositiveIntegerField(default=1, help_text='How many people including the requester', validators=[django.core.validators.MinValueValidator(1)])),
                ('message', models.TextField(blank=True, help_text='Optional note to the post owner')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='accepted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_requests', to='ride_share.ridepost')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_join_requests', to=settings.AUTH_USER_MODEL)),
                ('ride_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='ride_share.ridepost')),
            ],
            options={
                'unique_together': {('ride_post', 'requester')},
            },
        ),
        migrations.CreateModel(
            name='RideGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_initiator', models.BooleanField(default=False, help_text='True for the post owner who created the ride')),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('left', 'Left'), ('no_show', 'No Show')], default='confirmed', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='ride_share.ridegroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_group_memberships', to=settings.AUTH_USER_MODEL)),
                ('join_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_membership', to='ride_share.ridejoinrequest')),
            ],
            options={
                'unique_together': {('group', 'user')},
            },
        ),
        migrations.CreateModel(
            name='RideRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('given_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='ride_share.ridegroup')),
                ('rated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_ratings_received', to=settings.AUTH_USER_MODEL)),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_ratings_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('group', 'rater', 'rated_user')},
            },
        ),
    ]
