# Generated by Django 6.0.4 on 2026-05-18 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride_share', '0003_remove_ridepost_destination_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ridepost',
            name='safety_mode',
        ),
    ]
