# Generated by Django 6.0.4 on 2026-05-18 08:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_share', '0004_remove_ridepost_safety_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ridegroupmember',
            name='join_request',
        ),
        migrations.AddField(
            model_name='ridegroupmember',
            name='party_size',
            field=models.PositiveIntegerField(default=1, help_text='How many people including the requester', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='ridegroupmember',
            name='is_initiator',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ridepost',
            name='departure_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ridepost',
            name='destination_location',
            field=models.CharField(blank=True, default='United International University, Madani Ave, Dhaka', max_length=255),
        ),
        migrations.AlterField(
            model_name='ridepost',
            name='direction',
            field=models.CharField(choices=[('to_university', 'Going to University'), ('to_home', 'Going Home')], default='to_university', max_length=20),
        ),
        migrations.AlterField(
            model_name='ridepost',
            name='expires_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ridepost',
            name='max_capacity',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='ridepost',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ridepost',
            name='starting_location',
            field=models.CharField(help_text='Your pickup area or landmark', max_length=255),
        ),
        migrations.DeleteModel(
            name='RideJoinRequest',
        ),
    ]
