# Generated by Django 6.0.4 on 2026-05-19 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride_share', '0005_remove_ridegroupmember_join_request_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RideRating',
        ),
    ]
