# Generated by Django 6.0.4 on 2026-05-19 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_share', '0006_delete_riderating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ridegroupmember',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('left', 'Left'), ('no_show', 'No Show')], default='confirmed', max_length=20),
        ),
    ]
