# Generated by Django 6.0.4 on 2026-05-13 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_exchange', '0005_sessionendrequest'),
        ('threads', '0009_threadmessage_is_pinned'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exchangematch',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='exchangematch',
            name='skill_a_offers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_offered_a', to='skill_exchange.skill'),
        ),
        migrations.AddField(
            model_name='exchangematch',
            name='skill_b_offers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_offered_b', to='skill_exchange.skill'),
        ),
        migrations.AlterField(
            model_name='exchangematch',
            name='ex_p_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_a', to='skill_exchange.exchangepost'),
        ),
        migrations.AlterField(
            model_name='exchangematch',
            name='ex_p_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_b', to='skill_exchange.exchangepost'),
        ),
        migrations.AlterUniqueTogether(
            name='exchangematch',
            unique_together={('ex_p_a', 'ex_p_b', 'skill_a_offers', 'skill_b_offers')},
        ),
        migrations.AlterUniqueTogether(
            name='exchangesession',
            unique_together={('match', 'thread')},
        ),
        migrations.AlterUniqueTogether(
            name='matchdecision',
            unique_together={('decided_by', 'exchange_match')},
        ),
        migrations.AlterUniqueTogether(
            name='sessionfeedback',
            unique_together={('rated_by_user', 'exchange_session')},
        ),
        migrations.AddConstraint(
            model_name='exchangematch',
            constraint=models.CheckConstraint(condition=models.Q(('ex_p_a__lt', models.F('ex_p_b'))), name='exchange_match_post_order'),
        ),
    ]
