# Generated by Django 6.0.4 on 2026-05-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_exchange', '0006_alter_exchangematch_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangepost',
            name='status',
            field=models.CharField(choices=[('matching', 'Matching'), ('deleted', 'Deleted')], default='matching', max_length=20),
        ),
    ]
