# Generated by Django 6.0.4 on 2026-05-14 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_exchange', '0007_alter_exchangepost_status'),
        ('threads', '0009_threadmessage_is_pinned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchangesession',
            old_name='ended_at',
            new_name='completed_at',
        ),
        migrations.AddField(
            model_name='exchangesession',
            name='user_a_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exchangesession',
            name='user_b_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='exchangematch',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='exchangesession',
            name='match',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_session', to='skill_exchange.exchangematch'),
        ),
        migrations.AlterField(
            model_name='exchangesession',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='exchangesession',
            name='thread',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_session', to='threads.thread'),
        ),
        migrations.DeleteModel(
            name='SessionEndRequest',
        ),
    ]
