# Generated by Django 6.0.4 on 2026-05-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_exchange', '0008_rename_ended_at_exchangesession_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangematch',
            name='user_a_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exchangematch',
            name='user_b_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='MatchDecision',
        ),
    ]
