# Generated by Django 6.0.4 on 2026-05-14 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_exchange', '0010_skill_status_alter_skill_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userskill',
            name='proficiency_level',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userskill',
            name='proficiency_method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userskill',
            name='proficiency_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userskill',
            name='years_experience',
            field=models.PositiveSmallIntegerField(blank=True, max_length=2, null=True),
        ),
    ]
