# Generated by Django 6.0.4 on 2026-05-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_exchange', '0011_userskill_proficiency_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userskill',
            name='years_experience',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
    ]
