# Generated by Django 6.0.4 on 2026-05-16 18:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_exchange', '0012_alter_userskill_years_experience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessionfeedback',
            old_name='given_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='sessionfeedback',
            old_name='comment',
            new_name='notes',
        ),
        migrations.AlterField(
            model_name='sessionfeedback',
            name='exchange_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='skill_exchange.exchangesession'),
        ),
        migrations.AlterField(
            model_name='sessionfeedback',
            name='rating',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
