# Generated by Django 6.0.4 on 2026-05-16 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skill_exchange', '0013_rename_given_at_sessionfeedback_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionfeedback',
            name='status',
        ),
    ]
